services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airflow  # for Airflow metadata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    platform: linux/arm64
    image: custom_airflow_pyspark:latest
    container_name: airflow
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      DATABASE_URL: postgresql://postgres:postgres@db:5432/medica
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: >
      bash -c "
        airflow db migrate &&
        airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com &&
        airflow scheduler & airflow webserver
      "

  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/medica?sslmode=disable

volumes:
  pgdata:
